// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryWebAPI.Data;

#nullable disable

namespace MusicLibraryWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231113192501_AddInitialData")]
    partial class AddInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryWebAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ez Come Ez Go"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cumin' Atcha Live"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gettin Better"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2 Late 4 Love"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rock Me To The Top"
                        },
                        new
                        {
                            Id = 6,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "We're No Good Together"
                        },
                        new
                        {
                            Id = 7,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Modern Day Cowboy"
                        },
                        new
                        {
                            Id = 8,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Changes"
                        },
                        new
                        {
                            Id = 9,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Little Suzi"
                        },
                        new
                        {
                            Id = 10,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Love Me"
                        },
                        new
                        {
                            Id = 11,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cover Queen"
                        },
                        new
                        {
                            Id = 12,
                            Album = "Mechanical Resonance",
                            Artist = "Tesla",
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Before My Eyes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
